name: Build and Deploy

on:
  push:
    branches: 
      -  main

jobs:
  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.10'
      - name: Install Project Dependencies
        run: npm ci
      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli@5.12.4
      - name: Build
        run: gatsby build
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: npm run deploy
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: badsyntax/github-action-aws-cloudfront@master
        name: Invalidate CloudFront Cache
        id: invalidate-cloudfront-cache
        with:
          distribution-id: ${{ secrets.CFDistributionId }}
          aws-region: 'us-east-1'
          invalidate-paths: '/*'
          default-root-object: 'index.html'
